Repository ViniciusKurek/CalculadoraAPS, pull requests merged in 2023-12, with the labels that each got.

#14 Números com virgula, porcentagem e radiciação
  calculator/components/CPULucio.cpp
  calculator/components/CPULucio.hpp
Labels: enhancement

#17 DSS trabalho final
  Trabalho final/5 - DSS/1 - Ver projetos.drawio
  Trabalho final/5 - DSS/1 - Ver projetos.jpg
  Trabalho final/5 - DSS/2 - Montar formulário.drawio
  Trabalho final/5 - DSS/2 - Montar formulário.jpg
  Trabalho final/5 - DSS/3 - Responder formulário.drawio
  Trabalho final/5 - DSS/3 - Responder formulário.jpg
  Trabalho final/5 - DSS/4 - Enviar feedback formulário.drawio
  Trabalho final/5 - DSS/4 - Enviar feedback formulário.jpg
  Trabalho final/5 - DSS/5 - Ver feedback formulário.drawio
  Trabalho final/5 - DSS/5 - Ver feedback formulário.jpg
  Trabalho final/5 - DSS/6 - Calcular resultados.drawio
  Trabalho final/5 - DSS/6 - Calcular resultados.jpg
  Trabalho final/Trabalho Final.docx
Labels: documentation

#19 Feito métodos de memória.
  calculator/components/CPULucio.cpp
  calculator/components/CPULucio.hpp
Labels: enhancement

#20 Atualizado DS
  Trabalho final/Trabalho Final.odt
Labels: documentation

#33 Adicionados alguns DCs
  Trabalho final/7 - DC/Enviar Feedback do form.drawio
  Trabalho final/7 - DC/Enviar Feedback do form.drawio.png
  Trabalho final/7 - DC/Montar Formulario.drawio
  Trabalho final/7 - DC/Montar Formulario.drawio.png
  Trabalho final/7 - DC/Responder Formulário.drawio
  Trabalho final/7 - DC/Responder Formulário.drawio.png
  Trabalho final/7 - DC/Ver Feedback do Form.drawio
  Trabalho final/7 - DC/Ver Feedback do Form.drawio.png
  Trabalho final/7 - DC/Ver Projetos.drawio
  Trabalho final/7 - DC/Ver Projetos.drawio.png
Labels: documentation

#34 Adicionados mais alguns DCs
  Trabalho final/7 - DC/Cadastrar Propriedade.drawio
  Trabalho final/7 - DC/Cadastrar Propriedade.drawio.png
  Trabalho final/7 - DC/Cadastrar Proprietario.drawio
  Trabalho final/7 - DC/Cadastrar Proprietario.drawio.png
  Trabalho final/7 - DC/Ver Feedback do Form.drawio
Labels: documentation

#35 Adicionados mais alguns DCs
  Trabalho final/7 - DC/Cadastrar Propriedade.drawio
  Trabalho final/7 - DC/Criar Projeto.drawio
  Trabalho final/7 - DC/Criar Projeto.drawio.png
  Trabalho final/7 - DC/Criar etapaProjeto.drawio
  Trabalho final/7 - DC/Criar etapaProjeto.drawio.png
Labels: documentation

#42 Corrigido problema de imprecisão e de estourar o limite de digitos.
  .gitignore
  calculator/components/CPULucio.cpp
  calculator/components/CPULucio.hpp
Labels: enhancement

#43 Corrigido Main para que funcione tanto no Windows quanto no Linux
  calculator/main.cpp
Labels: bug, enhancement

#46 Corrigidos alguns problemas da calculadora
  .gitignore
  calculator/components/CPULucio.cpp
  calculator/components/CPULucio.hpp
  calculator/components/DisplayNat.cpp
  calculator/main.cpp
Labels: enhancement

#48 Calculadora Final
  README.md
  calculator/components/CPULucio.cpp
  calculator/components/CPULucio.hpp
  calculator/components/DisplayNat.cpp
  calculator/main.cpp
Labels: documentation, enhancement
